<?php
/**
 * Setup script to create config.php if it doesn't exist
 * This will be run automatically on first API call, or can be run manually
 */

$configFile = __DIR__ . '/config.php';
$templateFile = __DIR__ . '/config-template.php';

// If config.php already exists, redirect to a success message
if (file_exists($configFile)) {
    header('Content-Type: application/json');
    echo json_encode([
        'success' => true,
        'message' => 'config.php already exists',
        'note' => 'If you need to recreate it, delete the existing file first'
    ]);
    exit;
}

// OVH Production database credentials
$ovhConfig = [
    'host' => 'elektry2025.mysql.db',
    'dbname' => 'elektry2025',
    'username' => 'elektry',
    'password' => '92Alcolea2025'
];

// Detect environment
$isLocal = (
    strpos($_SERVER['HTTP_HOST'] ?? '', 'localhost') !== false ||
    strpos($_SERVER['HTTP_HOST'] ?? '', '127.0.0.1') !== false ||
    strpos(__DIR__, '/Users/') !== false
);

// Create config.php content
if ($isLocal) {
    // Local development - use template
    if (file_exists($templateFile)) {
        $configContent = file_get_contents($templateFile);
        $configContent = str_replace(
            ["'localhost'", "'elektr_ame'", "'root'", "''"],
            ["'localhost'", "'elektr_ame'", "'root'", "''"],
            $configContent
        );
    } else {
        // Fallback template
        $configContent = <<<'PHP'
<?php
// Database configuration for Elektr-Âme
// Auto-generated by setup-config.php

// Database configuration
$host = 'localhost';
$dbname = 'elektr_ame';
$username = 'root';
$password = '';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
} catch (PDOException $e) {
    error_log("Database connection failed: " . $e->getMessage());
    die(json_encode(['success' => false, 'message' => 'Database connection failed']));
}
?>
PHP;
    }
} else {
    // OVH Production
    $configContent = <<<PHP
<?php
// Database configuration for Elektr-Âme
// Auto-generated by setup-config.php for OVH Production

\$host = "{$ovhConfig['host']}";
\$dbname = "{$ovhConfig['dbname']}";
\$username = "{$ovhConfig['username']}";
\$password = "{$ovhConfig['password']}";

try {
    \$pdo = new PDO("mysql:host=\$host;dbname=\$dbname;charset=utf8mb4", \$username, \$password);
    \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    \$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    \$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
} catch (PDOException \$e) {
    error_log("Database connection failed: " . \$e->getMessage());
    die(json_encode(['success' => false, 'message' => 'Database connection failed']));
}
?>
PHP;
}

// Write config.php
try {
    file_put_contents($configFile, $configContent);
    chmod($configFile, 0600); // Secure permissions
    
    // Test the connection
    require_once $configFile;
    
    header('Content-Type: application/json');
    echo json_encode([
        'success' => true,
        'message' => 'config.php created successfully',
        'environment' => $isLocal ? 'local' : 'production',
        'database' => $isLocal ? 'elektr_ame (local)' : $ovhConfig['dbname'],
        'test' => 'Connection test passed'
    ]);
} catch (Exception $e) {
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'message' => 'Failed to create config.php',
        'error' => $e->getMessage()
    ]);
}
?>

