name: Deploy to OVH

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Deploy to OVH via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./www/
        
    - name: Deploy PHP API
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        local-dir: ./api/
        server-dir: ./www/api/
        
    - name: Deploy database schema
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        local-dir: ./database/
        server-dir: ./www/database/









